services:
  backend:
    build:
      context: ./backend
    image: ilenisnerd/docker-project-backend:latest
    container_name: momo-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - app-network
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

  frontend:
    build:
      context: ./frontend
    image: ilenisnerd/docker-project-frontend:latest
    container_name: momo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
    volumes:
      - nginx-logs:/var/log/nginx:rw

networks:
  app-network:
    name: momo-app-network
    driver: bridge

volumes:
  nginx-logs:
    name: momo-nginx-logs